filter:
    paths:
        - src
    excluded_paths:
        - vendor
before_commands:
    - 'composer install --dev --prefer-source'
tools:
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_cpd: true
    php_loc: true
    php_pdepend: true